Kartverket/Models/ErrorViewModel.cs
namespace Kartverket.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Kartverket/Models/FaultReportModel.cs
using System.ComponentModel.DataAnnotations;

namespace Kartverket.Models
{
    public class FaultReportModel
    {

        [Key]
        public int ReportId { get; set; }

        [Required]
        public double Longitude { get; set; }
        [Required]
        public double Latitude { get; set; }
        [Required]
        public string Description { get; set; }
    }
}

Kartverket/Controllers/FaultReportController.cs
using Kartverket.Data;
using Kartverket.Models; 
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Kartverket.Controllers
{
    public class FaultReportController : Controller
    {
        private readonly KartverketDbContext _kartverketDbContext;

        public FaultReportController(KartverketDbContext kartverketDbContext)
        {
            _kartverketDbContext = kartverketDbContext;
        }

        [HttpGet]
        public IActionResult FaultReportForm()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddToFaultReportForm(FaultReportModel faultReportModel)
        {
            if (faultReportModel == null)
            {
                return BadRequest();
            }

            var faultReport = new FaultReportModel
            {
                Longitude = faultReportModel.Longitude,
                Latitude = faultReportModel.Latitude,
                Description = faultReportModel.Description
            };

            await _kartverketDbContext.FaultReports.AddAsync(faultReport);
            await _kartverketDbContext.SaveChangesAsync();

            return RedirectToAction("FaultReportList");
        }

        [HttpGet]
        [ActionName("FaultReportList")]
        public async Task<IActionResult> FaultReportList()
        {
            var faultReports = await _kartverketDbContext.FaultReports.ToListAsync();

            return View(faultReports);
        }

        
    }
}

Kartverket/Controllers/HomeController.cs
using Kartverket.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Kartverket.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Kartverket/Views/FaultReport/FaultReportEdit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Kartverket/Views/FaultReport/FaultReportForm.cshtml
@model Kartverket.Models.FaultReportModel 

@{
}



<div class="container py-5">
    <form method="post">
        <div class="mb-3">
            <label class="form-label">Latitude</label>
            <input type="text" class="form-control" id="latitude" asp-for="Latitude" />
        </div>

        <div class="mb-3">
            <label class="form-label">Longitude</label>
            <input type="text" class="form-control" id="longitude" asp-for="Longitude" />
        </div>

        <div class="mb-3">
            <label class="form-label">Description</label>
            <input type="text" class="form-control" id="description" asp-for="Description" />
        </div>

        <div class="mb-3">
            <button type="submit" class="btn btn-dark">Submit</button>
        </div>

    </form>

</div>

Kartverket/Views/FaultReport/FaultReportList.cshtml
@model List<Kartverket.Models.FaultReportModel>

@{
}


<div>
@if (Model != null && Model.Any())
{
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Longitude</th>
                <th>Latitude</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var faultReport in Model)
            {
                <tr>
                    <td>@faultReport.ReportId</td>
                    <td>@faultReport.Longitude</td>
                    <td>@faultReport.Latitude</td>
                    <td>@faultReport.Description</td>
                    <td>
                        <a asp-area=""
                           asp-controller="AdminTags"
                           asp-action="Edit"
                           asp-route-id="@faultReport.ReportId">Edit</a>
                    </td>
                </tr>

            }
        </tbody>
    </table>
}
else
{
    <p>No tags found!</p>
}
</div>

Kartverket/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<head>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
          integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
          crossorigin="" />
    
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
            integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
            crossorigin=""></script>
</head>


<div class="text-center">
    
</div>

<div id="map"></div>
<script src="~/js/site.js"></script>

Kartverket/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Kartverket</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Kartverket.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/karverket_logo_hori.svg" alt="Kartverket Logo" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FaultReport" asp-action="FaultReportForm">Innmelding</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FaultReport" asp-action="FaultReportList">Oversikt</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Kartverket - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>